### ISSUE TITLE
HI,there is a little problem with my code-env

### ISSUE THREAD

**Issue by overxp** [stscl/esp#11]
**When I run the following code**
go1 = esp(y ~., data = final_data, discvar = names(select(final_data,-c(y))),wt = wt3,
           overlay = 'intersection')

**It says** 

Using Python: D:/application/miniconda3/python.exe
Creating virtual environment "r-reticulate" ...
**the error message is**

Error in gdverse_pyinit() : 
  python dependencies for gdverse cannot be loaded properly.

**Comment by SpatLyu** [comment]
Please provide a minimal reproducible example; `esp` does not call any functions from `gdverse`. Please reinstall `esp` and test the data again. Thank you.

**Comment by SpatLyu** [comment]
Please reset your conda env, you can refer to [this](https://ausgis.github.io/gdverse/articles/rgdrid.html).
